---
apiVersion: v1
kind: Namespace
metadata:
  name: s3-ls
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: s3-ls
  namespace: s3-ls
  labels:
    app: s3-ls
spec:
  selector:
    matchLabels:
      app: s3-ls
  template:
    metadata:
      labels:
        app: s3-ls
    spec:
      containers:
      - name: s3-ls
        image: amazon/aws-cli:latest
        command: ["/bin/sh"]
        args: ["-c", "while true; do aws s3 ls; sleep 10; done"]
        resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "64Mi"
          cpu: "250m"
      restartPolicy: Always
