spec:
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/askulkarni2/crossplane-irsa-sample-app
    targetRevision: HEAD
  syncPolicy:
    automated:
      allowEmpty: false
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: "10s"
        factor: 2
        maxDuration: "3m"
    syncOptions:
      - "Validate=false"
      - "CreateNamespace=true"
      - "PrunePropagationPolicy=foreground"
      - "PruneLast=true"
