spec:
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/askulkarni2/crossplane-irsa-sample-app
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - Validate=false
    - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m