---
apiVersion: awsblueprints.io/v1alpha1
kind: IRSA
metadata:
  name: "s3-ls-irsa"
spec:
  awsAccountID: "829527579886"
  eksOIDC: oidc.eks.us-east-1.amazonaws.com/id/8CA6195845CF282B3E5B1B605F5C9E75
  policyArns:
    - "arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess"
  serviceAccountName: "s3-ls"
  resourceConfig:
    providerConfigName: default
    region: us-east-1
    tags:
      - key: env
        value: test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: s3-ls
  namespace: default
  labels:
    app: s3-ls
spec:
  selector:
    matchLabels:
      app: s3-ls
  template:
    metadata:
      labels:
        app: s3-ls
    spec:
      serviceAccountName: s3-ls
      containers:
      - name: s3-ls
        image: amazon/aws-cli:latest
        command: ["/bin/sh"]
        args: ["-c", "while true; do aws s3 ls; sleep 10; done"]
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "64Mi"
            cpu: "250m"
      restartPolicy: Always
